version: '3.7'

services:
  app:
    build: .
    command: sh -c "rm -f /sfhelpdesk/tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sfhelpdesk
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/sfhelpdesk_development
    stdin_open: true
    tty: true
  
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: 'redis:6.2.14-alpine'
    restart: always
    command: "redis-server"
    volumes:
      - redis:/data
    ports:
      - "6379:6379" 
  
volumes:
  dbdata:
  redis: